#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.


def fibonacci(n, limit):
	seq = [1,2]
	while n > len(seq):
		next_fibonacci = seq[-1] + seq[-2]
		seq.append(next_fibonacci)
		if next_fibonacci > limit:
			seq.pop()
			return seq
	return seq
full_list = fibonacci(40, 4000000)
result = 0
for item in full_list:
	if item%2 == 0:
		result += item
print result